In [35]:
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        return self.sigmoid(self.linear(features))

In [36]:
features = torch.rand(10,5)

model = Model(features.shape[1])
model(features)

tensor([[0.5232],
        [0.5334],
        [0.5605],
        [0.5629],
        [0.5405],
        [0.5841],
        [0.5393],
        [0.5278],
        [0.5017],
        [0.4894]], grad_fn=<SigmoidBackward0>)

In [37]:
model.linear.weight

Parameter containing:
tensor([[ 0.1479,  0.3904, -0.0378, -0.1158,  0.1102]], requires_grad=True)

In [38]:
model.linear.bias

Parameter containing:
tensor([-0.1304], requires_grad=True)

In [39]:
# !pip install torchinfo

In [40]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [43]:
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        x = self.relu(self.linear1(features))
        return self.sigmoid(self.linear2(x))

In [44]:
features = torch.rand(10,5)

model = Model(features.shape[1])
model(features)

tensor([[0.5651],
        [0.5660],
        [0.5498],
        [0.5547],
        [0.5582],
        [0.5644],
        [0.5614],
        [0.5574],
        [0.5625],
        [0.5523]], grad_fn=<SigmoidBackward0>)

In [45]:
model.linear1.weight

Parameter containing:
tensor([[ 0.0341,  0.0244,  0.3424, -0.2658, -0.0838],
        [ 0.0525,  0.0315, -0.0662, -0.3497, -0.3460],
        [ 0.0979, -0.0232, -0.1034,  0.3055, -0.0414]], requires_grad=True)

In [46]:
model.linear2.weight

Parameter containing:
tensor([[0.1716, 0.3153, 0.4185]], requires_grad=True)

In [47]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [48]:
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        return self.network(features)

In [49]:
features = torch.rand(10,5)
model = Model(features.shape[1])
model(features)

tensor([[0.4938],
        [0.5156],
        [0.5162],
        [0.4947],
        [0.5026],
        [0.5026],
        [0.4835],
        [0.4940],
        [0.5026],
        [0.4704]], grad_fn=<SigmoidBackward0>)