# What are Tensors ?

A tensor is a specialised multi-dimensional array designed for mathematical and computational efficiency. In deep learning and machine learning, tensors are used to store and process data efficiently. The dimension of a tensor represents in how many directions the data is spanning.

For example:
- A scalar has 0 dimensions.
- A vector has 1 dimension.
- A matrix has 2 dimensions.

As dimensions increase, tensors can represent more complex data like images, batches of images, and videos.

## Real World Examples of Tensors

### 1. Scalars : 0-Dimensional Tensors

A scalar is a single numerical value. It does not have any direction or axis.

- Represents a single value, often used for simple metrics or constants.
- Commonly used for loss values, accuracy scores, or constants.

**Example:**
- Loss value after a forward pass in a neural network.
- Values like `5.0` or `-3.14`

---

### 2. Vectors : 1-Dimensional Tensors

A vector is a collection of numbers arranged in a single direction.

- Represents a sequence or collection of values.
- Frequently used in embeddings and feature representations.

**Example:**
- Word embeddings in NLP.

```python
[0.12, -0.84, 0.33]
```

This vector can represent the semantic meaning of a word using models like Word2Vec or GloVe.

---

### 3. Matrices : 2-Dimensional Tensors

A matrix is a grid-like structure containing rows and columns.

- Represents tabular or structured data.
- Often used to represent grayscale images.

**Example:**

```python
[
 [0, 255, 128],
 [34, 90, 180]
]
```

Each value represents the intensity of a pixel in a grayscale image.

---

### 4. 3D Tensors : Coloured Images

A 3D tensor adds another dimension to store channels.

- Commonly used for RGB images.
- Shape format:

```python
[height, width, channels]
```

**Example:**

```python
[256, 256, 3]
```

Here:
- `256 × 256` = image size
- `3` = RGB colour channels

---

### 5. 4D Tensors : Batches of Images

A 4D tensor adds the batch dimension to 3D image data.

- Used when training neural networks on multiple images together.
- Shape format:

```python
[batch_size, height, width, channels]
```

**Example:**

```python
[32, 128, 128, 3]
```

This means:
- 32 images
- Each image size is `128 × 128`
- 3 RGB channels

---

### 6. 5D Tensors : Video Data

A 5D tensor adds a time dimension to represent sequential frames.

- Used in video processing and action recognition tasks.
- Shape format:

```python
[batch_size, frames, height, width, channels]
```

**Example:**

```python
[10, 16, 64, 64, 3]
```

This represents:
- 10 video clips
- Each clip contains 16 frames
- Each frame size is `64 × 64`
- 3 RGB channels

# Why are Tensors Useful ?

Tensors are the foundation of deep learning because they allow efficient storage and computation of data.

## Mathematical Operations

Tensors support efficient mathematical operations such as:
- Addition
- Multiplication
- Dot products
- Broadcasting
- Matrix multiplication

These operations are essential for neural network computations.

---

## Representation of Real World Data

Different types of real-world data can be represented using tensors:

- Images → 3D tensors
- Text → 2D or 3D tensors
- Audio → Sequential tensors
- Videos → 5D tensors

This makes tensors highly flexible for AI applications.

---

## Efficient Computation

Tensor operations are highly optimized for hardware acceleration.

- GPUs and TPUs process tensors very efficiently.
- This significantly speeds up deep learning training and inference.

# Where are Tensors Used in Deep Learning ?

## Data Storage

Training data such as:
- Images
- Text
- Audio
- Videos

are stored in tensor format.

---

## Weights and Biases

The learnable parameters of neural networks, such as:
- Weights
- Biases

are stored as tensors.

---

## Matrix Operations

Neural networks perform operations like:
- Matrix multiplication
- Dot products
- Broadcasting

All these computations are performed using tensors.

---

## Training Process

During training:
- Tensors flow through the network during forward propagation.
- Gradients are computed as tensors during backpropagation.

These gradients help the model learn and update its parameters.

In [567]:
import torch
print(torch.__version__)

2.10.0+cu128


In [568]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [569]:
# using empty
a = torch.empty(2,3)
print(a)
# check type
print(type(a))

tensor([[1.0019e-40, 0.0000e+00, 5.0447e-44],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
<class 'torch.Tensor'>


In [570]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [571]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [572]:
# using rand
torch.rand(2,3)

tensor([[0.6715, 0.5900, 0.6289],
        [0.4883, 0.7553, 0.5075]])

In [573]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [574]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [575]:
# other ways

# arange
print("using arange : ", torch.arange(0,10))

# using linspace
print("using linspace : ", torch.linspace(0,10,10))

# using eye
print("using eye : ", torch.eye(3))

# using ones_like
a = torch.rand(2,3)
print("using ones_like : ", torch.ones_like(a))

# using full
print("using full : ", torch.full((2,3), 5))

using arange :  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace :  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye :  tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
using ones_like :  tensor([[1., 1., 1.],
        [1., 1., 1.]])
using full :  tensor([[5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [576]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [577]:
x.shape

torch.Size([2, 3])

In [578]:
torch.empty_like(x)

tensor([[109322,      5,      5],
        [     5,      5,      5]])

In [579]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [580]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [581]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

## Tensor Data Types

| Data Type | Dtype | Description |
|---|---|---|
| 32-bit Floating Point | `torch.float32` | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage. |
| 64-bit Floating Point | `torch.float64` | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory. |
| 16-bit Floating Point | `torch.float16` | Half precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs. |
| BFloat16 | `torch.bfloat16` | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs. |
| 8-bit Floating Point | `torch.float8` | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments. |
| 8-bit Integer | `torch.int8` | 8-bit signed integer. Used for quantized models to save memory and computation in inference. |
| 16-bit Integer | `torch.int16` | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision. |
| 32-bit Integer | `torch.int32` | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks. |
| 64-bit Integer | `torch.int64` | Long integer type. Often used for large indexing arrays or tasks involving large numbers. |
| 8-bit Unsigned Integer | `torch.uint8` | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255). |
| Boolean | `torch.bool` | Boolean type, stores `True` or `False` values. Often used for masks in logical operations. |
| Complex 64 | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks. |
| Complex 128 | `torch.complex128` | Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory. |
| Quantized Integer | `torch.qint8` | Quantized signed 8-bit integer. Used in quantized models for efficient inference. |
| Quantized Unsigned Integer | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks. |

In [582]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [583]:
x.dtype

torch.int64

In [584]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [585]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [586]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical Operation

#### scaler operations

In [587]:
x = torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [588]:
print(x + 2)
print(x - 2)
print(x / 2)
print(x // 2)
print(x * 2)
print(x**2)

tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])
tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])
tensor([[0.1119, 0.1512],
        [0.0892, 0.4119]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0.4478, 0.6047],
        [0.3568, 1.6477]])
tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])


In [589]:
(x*100)//3

tensor([[ 7., 10.],
        [ 5., 27.]])

In [590]:
((x*100)//3)%2

tensor([[1., 0.],
        [1., 1.]])

#### Element Wise Operation

In [591]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [592]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a%b)

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])
tensor([[ 0.3132,  0.2767, -0.0837],
        [ 0.7007, -0.0464,  0.0657]])
tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])
tensor([[2.2912, 1.3951, 0.8415],
        [3.8346, 0.9413, 1.1552]])
tensor([[0.8672, 0.9839, 0.6515],
        [0.9868, 0.7919, 0.7388]])
tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])


In [593]:
c = torch.tensor([1, -2, 3, -4])
c

tensor([ 1, -2,  3, -4])

In [594]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [595]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [596]:
torch.round(c)

tensor([ 1, -2,  3, -4])

In [597]:
torch.ceil(c)

tensor([ 1, -2,  3, -4])

In [598]:
torch.floor(c)

tensor([ 1, -2,  3, -4])

In [599]:
torch.clamp(c, min=2, max=3)

tensor([2, 2, 3, 2])

#### Reduction Operation

In [600]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[5, 7, 3],
        [9, 4, 0]])

In [601]:
torch.sum(e)

tensor(28)

In [602]:
torch.sum(e, dim=0)

tensor([14, 11,  3])

In [603]:
torch.sum(e, dim=1)

tensor([15, 13])

In [604]:
torch.mean(e, dtype=torch.float32)

tensor(4.6667)

In [605]:
torch.mean(e, dim=0, dtype=torch.float32)

tensor([7.0000, 5.5000, 1.5000])

In [606]:
torch.median(e)

tensor(4)

In [607]:
torch.max(e)

tensor(9)

In [608]:
torch.min(e)

tensor(0)

In [609]:
torch.prod(e)

tensor(0)

In [610]:
torch.std(e.to(torch.float32))

tensor(3.1411)

In [611]:
torch.var(e.to(torch.float32))

tensor(9.8667)

In [612]:
torch.argmax(e)

tensor(3)

In [613]:
torch.argmin(e)

tensor(5)

#### Matrix Operations

In [614]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(2,3), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9, 8],
        [9, 7, 9]])


In [615]:
torch.matmul(f, g.T)

tensor([[128, 139],
        [182, 207]])

In [616]:
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])

torch.dot(vector1, vector2)

tensor(32)

In [617]:
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [618]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[2., 6., 7.],
        [7., 8., 3.],
        [6., 1., 5.]])

In [619]:
torch.det(h)

tensor(-315.)

In [620]:
torch.inverse(h)

tensor([[-0.1175,  0.0730,  0.1206],
        [ 0.0540,  0.1016, -0.1365],
        [ 0.1302, -0.1079,  0.0825]])

#### Comparison Operations

In [621]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 0, 4],
        [3, 8, 8]])
tensor([[3, 3, 5],
        [0, 6, 4]])


In [622]:
i > j
i < j
i == j
i != j
i >= j
i <= j

tensor([[False,  True,  True],
        [False, False, False]])

#### Special Functions

In [623]:
k = torch.randint(size=(2,3), low=0, high=10)
k

tensor([[0, 8, 4],
        [7, 2, 3]])

In [624]:
torch.log(k)

tensor([[  -inf, 2.0794, 1.3863],
        [1.9459, 0.6931, 1.0986]])

In [625]:
torch.exp(k)

tensor([[1.0000e+00, 2.9810e+03, 5.4598e+01],
        [1.0966e+03, 7.3891e+00, 2.0086e+01]])

In [626]:
torch.sqrt(h)

tensor([[1.4142, 2.4495, 2.6458],
        [2.6458, 2.8284, 1.7321],
        [2.4495, 1.0000, 2.2361]])

In [627]:
torch.sigmoid(k.to(torch.float32))

tensor([[0.5000, 0.9997, 0.9820],
        [0.9991, 0.8808, 0.9526]])

In [628]:
torch.softmax(k.to(torch.float32), dim=0)

tensor([[9.1105e-04, 9.9753e-01, 7.3106e-01],
        [9.9909e-01, 2.4726e-03, 2.6894e-01]])

In [629]:
torch.relu(k)

tensor([[0, 8, 4],
        [7, 2, 3]])

## Inplace Operations

In [630]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])
tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [631]:
m.add_(n)

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [632]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [633]:
n

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [634]:
torch.relu(m)

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [635]:
m.relu_()

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [636]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

## Copying a Tensor

In [637]:
a = torch.rand(2, 3)
a

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [638]:
b = a

In [639]:
b

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [640]:
a[0][0] = 0

In [641]:
a

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [642]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [643]:
id(a) == id(b)

True

In [644]:
b = a.clone()
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [645]:
id(a) == id(b)

False

In [646]:
a[1][1] = 0

In [647]:
a

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.0000, 0.1893]])

In [648]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

## Tensors Operations on GPU

In [649]:
torch.cuda.is_available()

True

In [650]:
device = torch.device('cuda')

In [651]:
torch.rand((2,3), device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [652]:
a

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.0000, 0.1893]])

In [653]:
b = a.to(device)
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.0000, 0.1893]], device='cuda:0')

In [654]:
b + 5

tensor([[5.0000, 5.8935, 5.0497],
        [5.1780, 5.0000, 5.1893]], device='cuda:0')

In [655]:
import torch
import time

# Define the size of the matrices
size = 10000  # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)  # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)  # Matrix multiplication on GPU
torch.cuda.synchronize()  # Ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

# Compare results
print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)

Time on CPU: 16.6383 seconds
Time on GPU: 0.5798 seconds

Speedup (CPU time / GPU time): 28.695049412128483


## Reshaping Tensors

In [656]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [657]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [658]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [659]:
b = torch.rand(2,3,4)
b

tensor([[[0.8881, 0.7989, 0.9514, 0.0141],
         [0.8903, 0.1649, 0.3162, 0.1331],
         [0.6763, 0.4254, 0.2375, 0.5430]],

        [[0.1174, 0.6532, 0.5115, 0.3094],
         [0.7907, 0.7351, 0.2693, 0.8009],
         [0.5839, 0.0061, 0.4671, 0.8243]]])

In [660]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [661]:
c = torch.rand(226,226,3)
c.unsqueeze(dim=0).shape

torch.Size([1, 226, 226, 3])

In [662]:
c = torch.rand(226,226,3)
c.unsqueeze(dim=1).shape

torch.Size([226, 1, 226, 3])

In [663]:
d = torch.rand(1,20)
d.squeeze().shape

torch.Size([20])

## NumPy and PyTorch

In [664]:
import numpy as np

In [665]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [666]:
b = a.numpy()
b

array([1, 2, 3])

In [667]:
print(type(a))
print(type(b))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [668]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [669]:
torch.from_numpy(c)

tensor([1, 2, 3])